server:
  ip: 127.0.0.1
  port: 8087
  servlet:
    context-path: /xd-account

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.147.216:33061/ty?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml

files:
  upload:
    #    \u4E0A\u4F20\u6587\u4EF6\u5B58\u653E\u7684\u4F4D\u7F6E
    path: D:/files/
#    path: /home/files
